spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-108-128-104-50.eu-west-1.compute.amazonaws.com:5432/df62218adkr7lo
    username: kfofanythgwkis
    password: 526c9a4e09b706b85f4bdd8ccf02b573c71a9d58320df7ac1a291442a76adba7
    pool-size: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true