spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://136.243.132.113:3306/s38_BoxingHouseDB
    username: u38_3nNUvsvgqB
    password: kK8S=NeQgOPHaKHt7.kti@C@
    pool-size: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: true